variables:
  CI_REGISTRY_IMAGE: $REGISTRY_USER/k8s-doctl:$CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_VERSION: 19.03.4
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - name: docker:$DOCKER_VERSION-dind

stages:
  - build-and-push

build-and-push:
  image: docker:$DOCKER_VERSION
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  stage: build-and-push
  script:
    - docker build --network host -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

